project:
  preferred_years: [2019, 2020, 2021, 2022, 2023, 2024]
  end_year: 2024
  max_rows: 5000000
  label_method: "firms"

data:
  sites:
    # Santa Barbara County
    - {name: "Montecito"}
    - {name: "Hope Ranch"}
    - {name: "San Roque / La Cumbre (foothills)"}
    - {name: "Santa Barbara - The Mesa"}
    # Ventura County
    - {name: "Thousand Oaks (WUI canyons)"}
    - {name: "Newbury Park (WUI canyons)"}
    - {name: "Moorpark (expanded VHFHSZ)"}
    - {name: "Simi Valley (canyon edges)"}
    - {name: "Ojai Valley"}
    - {name: "Ventura Hillsides (Clearpoint/Ondulando/Skyline)"}
    - {name: "Fillmore (north/inland)"}
    - {name: "Santa Paula (north/inland)"}
    # Los Angeles County
    - {name: "Malibu (Santa Monica Mountains)"}
    - {name: "Santa Monica Mountains Interior"}
    - {name: "Glendale / Pasadena / Altadena / La Cañada Foothills"}
    - {name: "Bel Air / Brentwood / Hollywood Hills / Pacific Palisades / Woodland Hills"}
    - {name: "Chatsworth / Porter Ranch (Santa Susana)"}
    - {name: "Eagle Rock / Highland Park / El Sereno (Eastside WUI)"}
    - {name: "Palos Verdes Peninsula"}
    - {name: "Antelope Valley fringe (Lancaster/Palmdale WUI)"}
  raws_station_ids: []        # optional explicit RAWS IDs; else nearest lookup in code

frap:
  bbox: [-119.828, 33.422, -117.274, 34.931]   # [minLon, minLat, maxLon, maxLat]
  year_min: 2019
  year_max: 2024
  simplify_tolerance: 0.0005   # ~50–100 m; raise to 0.001 if frontend feels heavy

labeling:
  buffer_km: 22
  min_confidence: 20
  fwi_threshold_quantile: 0.9

features:
  lag_days: 7
  roll_window: 7
  use_neighbors: false
  k_neighbors: 5
  neighbor_radius_km: 50

train:
  model: "ann"
  epochs: 60
  batch: 256
  lr: 0.001
  class_weight: true
