// Sample forecast data and helpers for the dashboard prototype.
//
// sample-forecast.json is generated by scripts/build_sample_data.py. Its
// weather rows come from data/trihourly_weather.csv; the sites and their risk
// values are fictional, illustrative samples. There is no model service.
import sample from "./sample-forecast.json";

export type RiskLevel = "Extreme" | "High" | "Moderate" | "Low";

export interface WeatherRow {
  time: string;
  temperature_2m: number;
  relative_humidity_2m: number;
  wind_speed_10m: number;
  precipitation: number;
  cloud_cover: number;
  soil_moisture_0_to_7cm: number;
}

export interface Site {
  id: string;
  name: string;
  county: string;
  lat: number;
  lon: number;
  risk: number[];
}

export interface SampleForecast {
  description: string;
  source: string;
  stepHours: number;
  threshold: number;
  region: { name: string; counties: string[]; bbox: number[] };
  weather: WeatherRow[];
  sites: Site[];
}

export const forecast: SampleForecast = sample;

export const LEVELS: {
  level: RiskLevel;
  min: number;
  color: string;
  range: string;
}[] = [
  { level: "Extreme", min: 0.75, color: "#d32f2f", range: "≥ 0.75" },
  { level: "High", min: 0.5, color: "#ed6c02", range: "0.50 – 0.75" },
  { level: "Moderate", min: 0.25, color: "#fbc02d", range: "0.25 – 0.50" },
  { level: "Low", min: 0, color: "#2e7d32", range: "< 0.25" },
];

export function getLevel(value: number) {
  return LEVELS.find((l) => value >= l.min) ?? LEVELS[LEVELS.length - 1];
}

export const HORIZONS = [24, 48, 72] as const;
export type Horizon = (typeof HORIZONS)[number];

export const FIRST_DATE = forecast.weather[0].time.slice(0, 10);
export const LAST_DATE = forecast.weather[forecast.weather.length - 1].time.slice(
  0,
  10
);

const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];
const pad = (n: number) => (n < 10 ? `0${n}` : String(n));

/** Times in the sample are local wall-clock times ("2023-08-16T21:00"). */
export const parseTime = (t: string) => new Date(`${t}:00`);

export function formatDay(t: string) {
  const d = parseTime(t);
  return `${d.getDate()} ${MONTHS[d.getMonth()]}`;
}

export function formatDayTime(t: string) {
  const d = parseTime(t);
  return `${formatDay(t)}, ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export function formatLongDayTime(t: string) {
  return `${DAYS[parseTime(t).getDay()]} ${formatDayTime(t)}`;
}

export function formatRange(from: string, to: string) {
  const a = parseTime(from);
  const b = parseTime(to);
  const year = b.getFullYear();
  if (a.getMonth() !== b.getMonth()) {
    return `${formatDay(from)} – ${formatDay(to)} ${year}`;
  }
  if (a.getDate() === b.getDate()) return `${formatDay(to)} ${year}`;
  return `${a.getDate()}–${b.getDate()} ${MONTHS[b.getMonth()]} ${year}`;
}

export interface SiteView extends Site {
  series: number[];
  peak: number;
  peakTime: string;
  peakWeather: WeatherRow;
  level: RiskLevel;
  color: string;
}

export interface ForecastView {
  times: string[];
  weather: WeatherRow[];
  sites: SiteView[];
  threshold: number;
  rangeLabel: string;
  peakSite: SiteView;
  aboveThreshold: number;
  maxTemp: WeatherRow;
  minHumidity: WeatherRow;
}

/** Slice the sample to a forecast window: start date + horizon in hours. */
export function computeView(startDate: string, horizon: number): ForecastView {
  const { weather, stepHours, threshold } = forecast;
  let start = weather.findIndex((w) => w.time >= `${startDate}T00:00`);
  if (start < 0) start = 0;
  const steps = Math.max(1, Math.round(horizon / stepHours));
  const end = Math.min(weather.length, start + steps);
  const rows = weather.slice(start, end);
  const times = rows.map((r) => r.time);

  const sites: SiteView[] = forecast.sites
    .map((s) => {
      const series = s.risk.slice(start, end);
      let peakIdx = 0;
      series.forEach((v, i) => {
        if (v > series[peakIdx]) peakIdx = i;
      });
      const peak = series[peakIdx];
      const level = getLevel(peak);
      return {
        ...s,
        series,
        peak,
        peakTime: times[peakIdx],
        peakWeather: rows[peakIdx],
        level: level.level,
        color: level.color,
      };
    })
    .sort((a, b) => b.peak - a.peak);

  const maxTemp = rows.reduce(
    (m, r) => (r.temperature_2m > m.temperature_2m ? r : m),
    rows[0]
  );
  const minHumidity = rows.reduce(
    (m, r) => (r.relative_humidity_2m < m.relative_humidity_2m ? r : m),
    rows[0]
  );

  return {
    times,
    weather: rows,
    sites,
    threshold,
    rangeLabel: formatRange(times[0], times[times.length - 1]),
    peakSite: sites[0],
    aboveThreshold: sites.filter((s) => s.peak >= threshold).length,
    maxTemp,
    minHumidity,
  };
}
